
relay:
  integration: # REQUIRED
  alias: # REQUIRED
  subtype:   # OPTIONAL
  env:
    # TODO: Replace these with the values for the selected
    # integration and subtype, see reference here: 
    # https://github.com/cortexapps/axon/blob/main/README.relay.md#environment-variables-summary
    #
    # GITHUB_API: "https://api.github.com"
    # GITHUB_GRAPHQL_API: "https://api.github.com/graphql"

replicaCount: 2

image:
  repository: ghcr.io/cortexapps/cortex-axon-agent
  tag: latest

resources:
  limits:
    memory: "512Mi"
    cpu: "500m"
  requests:
    memory: "256Mi"
    cpu: "250m"

# ssl:
#   DisableTLS: false # set to true to disable SSL verification for DEBUGGING ONLY
#   caCertPath: # path where PEM files are located
#   certSecretName: # name of the secret containing a PEM file