
relay:
  integration: # REQUIRED
  alias: # REQUIRED
  subtype:   # OPTIONAL
  env:
    # TODO: Replace these with the values for the selected
    # integration and subtype, see reference here: 
    # https://github.com/cortexapps/axon/blob/main/README.relay.md#environment-variables-summary
    #
    # GITHUB_API: "https://api.github.com"
    # GITHUB_GRAPHQL_API: "https://api.github.com/graphql"
  verbose: false # set to true to enable verbose logging

replicaCount: 2

image:
  repository: ghcr.io/cortexapps/cortex-axon-agent
  tag: latest

resources:
  limits:
    memory: "512Mi"
    cpu: "500m"
  requests:
    memory: "256Mi"
    cpu: "250m"

# proxy:
#   server:  # set to the proxy server URL, e.g. http://proxy.example.com:8080
#   noProxy: # a comma-separated list of addresses to exclude from proxying
#   disableTLS: false # set to true to disable SSL verification for DEBUGGING ONLY
#   certSecretName: # name of the secret containing a .pem file with the CA certificate