apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.relay.integration }}.{{ .Values.relay.alias }}
  labels:
    app: {{ .Chart.Name }}-{{ .Values.relay.integration }}.{{ .Values.relay.alias }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
        env:
          {{- if (.Values.proxy).disableTLS }}
          - name: DISABLE_TLS
            value: "true"
          {{- end }}
          {{- if or (.Values.proxy).certSecretName }}
          - name: CA_CERT_PATH
            value: /etc/ssl/axon-certs
          {{- end }}
          {{- if (.Values.proxy).server }}
          - name: HTTP_PROXY
            value: {{ .Values.proxy.server }}
          - name: HTTPS_PROXY
            value: {{ .Values.proxy.server }}
          {{- end }}
          {{- if (.Values.proxy).noProxy }}
          - name: NO_PROXY
            value: {{ .Values.proxy.noProxy }}
          {{- end }}
         
        envFrom:
        - secretRef:
            name: axon-secrets
        - configMapRef:
            name: axon-config-{{ .Values.relay.integration }}.{{ .Values.relay.alias }}
        resources:
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
        args: 
          - relay
          - -i
          - {{ .Values.relay.integration }}
          {{- if .Values.relay.subtype }}
          - -s
          - {{ .Values.relay.subtype }}
          {{- end }}
          - -a
          - {{ .Values.relay.alias }}
          {{- if .Values.relay.verbose }}
          - -v
          {{- end }}
      {{- if (.Values.proxy).certSecretName }}
        volumeMounts:
          - name:  {{ .Release.Name }}-ssl-cert-volume
            mountPath: /etc/ssl/axon-certs
            readOnly: true
      volumes:
        - name: {{ .Release.Name }}-ssl-cert-volume
          secret:
            secretName: {{ .Values.proxy.certSecretName }}
      {{- end }}

    