apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.relay.integration }}.{{ .Values.relay.alias }}
  labels:
    app: {{ .Chart.Name }}-{{ .Values.relay.integration }}.{{ .Values.relay.alias }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: IfNotPresent
        env:
          {{- if (.Values.ssl).DisableTLS }}
          - name: DISABLE_TLS
            value: "true"
          {{- end }}
          {{- if or (.Values.ssl).certSecretName (.Values.ssl).caCertPath }}
          - name: CA_CERT_PATH
            value: /etc/ssl/axon-certs
          {{- end }}
         
        envFrom:
        - secretRef:
            name: axon-secrets
        - configMapRef:
            name: axon-config-{{ .Values.relay.integration }}.{{ .Values.relay.alias }}
        resources:
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
        args: 
          - relay
          - -i
          - {{ .Values.relay.integration }}
          {{- if .Values.relay.subtype }}
          - -s
          - {{ .Values.relay.subtype }}
          {{- end }}
          - -a
          - {{ .Values.relay.alias }}
      {{- if or (.Values.ssl).caCertPath (.Values.ssl).certSecretName }}
        volumeMounts:
          - name:  {{ .Release.Name }}-ssl-cert-volume
            mountPath: /etc/ssl/axon-certs
            readOnly: true
      {{- end }}
      {{- if (.Values.ssl).caCertPath }}
        volumes:
          - name: {{ .Release.Name }}-ssl-cert-volume
            secret:
              secretName: {{ .Release.Name }}-axon-ca-cert
      {{- else if (.Values.ssl).certSecretName }}
        volumes:
          - name: {{ .Release.Name }}-ssl-cert-volume
            secret:
              secretName: {{ .Values.ssl.certSecretName }}
      {{- end }}

    