// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: tunnel.proto

package tunnelpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CallStart_Kind int32

const (
	CallStart_UNARY         CallStart_Kind = 0
	CallStart_SERVER_STREAM CallStart_Kind = 1
	CallStart_CLIENT_STREAM CallStart_Kind = 2
	CallStart_BIDI          CallStart_Kind = 3
)

// Enum value maps for CallStart_Kind.
var (
	CallStart_Kind_name = map[int32]string{
		0: "UNARY",
		1: "SERVER_STREAM",
		2: "CLIENT_STREAM",
		3: "BIDI",
	}
	CallStart_Kind_value = map[string]int32{
		"UNARY":         0,
		"SERVER_STREAM": 1,
		"CLIENT_STREAM": 2,
		"BIDI":          3,
	}
)

func (x CallStart_Kind) Enum() *CallStart_Kind {
	p := new(CallStart_Kind)
	*p = x
	return p
}

func (x CallStart_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CallStart_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_tunnel_proto_enumTypes[0].Descriptor()
}

func (CallStart_Kind) Type() protoreflect.EnumType {
	return &file_tunnel_proto_enumTypes[0]
}

func (x CallStart_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CallStart_Kind.Descriptor instead.
func (CallStart_Kind) EnumDescriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{6, 0}
}

// Client → Server envelope.
type ClientFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ClientFrame_Hello
	//	*ClientFrame_Heartbeat
	//	*ClientFrame_Call
	Msg           isClientFrame_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientFrame) Reset() {
	*x = ClientFrame{}
	mi := &file_tunnel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientFrame) ProtoMessage() {}

func (x *ClientFrame) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientFrame.ProtoReflect.Descriptor instead.
func (*ClientFrame) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{0}
}

func (x *ClientFrame) GetMsg() isClientFrame_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ClientFrame) GetHello() *ClientHello {
	if x != nil {
		if x, ok := x.Msg.(*ClientFrame_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ClientFrame) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Msg.(*ClientFrame_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *ClientFrame) GetCall() *CallFrame {
	if x != nil {
		if x, ok := x.Msg.(*ClientFrame_Call); ok {
			return x.Call
		}
	}
	return nil
}

type isClientFrame_Msg interface {
	isClientFrame_Msg()
}

type ClientFrame_Hello struct {
	Hello *ClientHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type ClientFrame_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type ClientFrame_Call struct {
	Call *CallFrame `protobuf:"bytes,3,opt,name=call,proto3,oneof"`
}

func (*ClientFrame_Hello) isClientFrame_Msg() {}

func (*ClientFrame_Heartbeat) isClientFrame_Msg() {}

func (*ClientFrame_Call) isClientFrame_Msg() {}

// Server → Client envelope.
type ServerFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ServerFrame_Hello
	//	*ServerFrame_Heartbeat
	//	*ServerFrame_Call
	Msg           isServerFrame_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerFrame) Reset() {
	*x = ServerFrame{}
	mi := &file_tunnel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerFrame) ProtoMessage() {}

func (x *ServerFrame) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerFrame.ProtoReflect.Descriptor instead.
func (*ServerFrame) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{1}
}

func (x *ServerFrame) GetMsg() isServerFrame_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ServerFrame) GetHello() *ServerHello {
	if x != nil {
		if x, ok := x.Msg.(*ServerFrame_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ServerFrame) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Msg.(*ServerFrame_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *ServerFrame) GetCall() *CallFrame {
	if x != nil {
		if x, ok := x.Msg.(*ServerFrame_Call); ok {
			return x.Call
		}
	}
	return nil
}

type isServerFrame_Msg interface {
	isServerFrame_Msg()
}

type ServerFrame_Hello struct {
	Hello *ServerHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type ServerFrame_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type ServerFrame_Call struct {
	Call *CallFrame `protobuf:"bytes,3,opt,name=call,proto3,oneof"`
}

func (*ServerFrame_Hello) isServerFrame_Msg() {}

func (*ServerFrame_Heartbeat) isServerFrame_Msg() {}

func (*ServerFrame_Call) isServerFrame_Msg() {}

// ClientHello is the first message sent by the client after opening a
// stream. It carries identity information and the Cortex-API-issued broker
// token.
type ClientHello struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Cortex-API-issued token, used for dispatch routing. Same token the
	// snyk-broker transport uses.
	BrokerToken string `protobuf:"bytes,1,opt,name=broker_token,json=brokerToken,proto3" json:"broker_token,omitempty"`
	// Client software version.
	ClientVersion string `protobuf:"bytes,2,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	// Tenant identifier from Cortex API registration.
	TenantId string `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Integration type, e.g. "github", "jira".
	Integration string `protobuf:"bytes,4,opt,name=integration,proto3" json:"integration,omitempty"`
	// Integration alias name.
	Alias string `protobuf:"bytes,5,opt,name=alias,proto3" json:"alias,omitempty"`
	// Unique agent instance ID (from config.InstanceId).
	InstanceId string `protobuf:"bytes,6,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	// Cortex API token for optional server-side JWT validation.
	CortexApiToken string `protobuf:"bytes,7,opt,name=cortex_api_token,json=cortexApiToken,proto3" json:"cortex_api_token,omitempty"`
	// Arbitrary metadata.
	Metadata      map[string]string `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientHello) Reset() {
	*x = ClientHello{}
	mi := &file_tunnel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientHello) ProtoMessage() {}

func (x *ClientHello) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientHello.ProtoReflect.Descriptor instead.
func (*ClientHello) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{2}
}

func (x *ClientHello) GetBrokerToken() string {
	if x != nil {
		return x.BrokerToken
	}
	return ""
}

func (x *ClientHello) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *ClientHello) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ClientHello) GetIntegration() string {
	if x != nil {
		return x.Integration
	}
	return ""
}

func (x *ClientHello) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *ClientHello) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *ClientHello) GetCortexApiToken() string {
	if x != nil {
		return x.CortexApiToken
	}
	return ""
}

func (x *ClientHello) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ServerHello is the response to ClientHello.
type ServerHello struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server hostname (HOSTNAME env var, or UUID fallback). The client uses
	// this for metrics tagging and to cap streams per server instance.
	ServerId string `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	// Server-generated UUID for this specific stream. Used in BROKER_SERVER
	// client-connected/deleted notifications to distinguish multiple streams
	// for the same token.
	StreamId string `protobuf:"bytes,2,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	// Interval at which the server sends heartbeats. The client should
	// respond within 2x this interval.
	HeartbeatIntervalMs int32 `protobuf:"varint,3,opt,name=heartbeat_interval_ms,json=heartbeatIntervalMs,proto3" json:"heartbeat_interval_ms,omitempty"`
	// Maximum CallData payload size the server accepts. The client caps its
	// outgoing frames accordingly. 0 means the default (1 MiB).
	MaxFrameBytes int32 `protobuf:"varint,4,opt,name=max_frame_bytes,json=maxFrameBytes,proto3" json:"max_frame_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerHello) Reset() {
	*x = ServerHello{}
	mi := &file_tunnel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerHello) ProtoMessage() {}

func (x *ServerHello) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerHello.ProtoReflect.Descriptor instead.
func (*ServerHello) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{3}
}

func (x *ServerHello) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ServerHello) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *ServerHello) GetHeartbeatIntervalMs() int32 {
	if x != nil {
		return x.HeartbeatIntervalMs
	}
	return 0
}

func (x *ServerHello) GetMaxFrameBytes() int32 {
	if x != nil {
		return x.MaxFrameBytes
	}
	return 0
}

// Heartbeat is sent by both sides to verify tunnel liveness while a stream
// is idle. While a call is active on a stream, heartbeat-timeout
// enforcement is relaxed: frame trafic proves liveness and transport-level
// gRPC keepalive covers dead TCP.
type Heartbeat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unix timestamp in milliseconds.
	TimestampMs   int64 `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_tunnel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{4}
}

func (x *Heartbeat) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

// CallFrame carries one event for one logical call. The direction of the
// enclosing envelope tells you who sent it: the server sends the request
// (Start/Data/End), the agent sends the response (Start/Data/End) with the
// same call_id. Either side may send Cancel at any time.
type CallFrame struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	CallId string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*CallFrame_Start
	//	*CallFrame_Data
	//	*CallFrame_End
	//	*CallFrame_Cancel
	Body          isCallFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallFrame) Reset() {
	*x = CallFrame{}
	mi := &file_tunnel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallFrame) ProtoMessage() {}

func (x *CallFrame) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallFrame.ProtoReflect.Descriptor instead.
func (*CallFrame) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{5}
}

func (x *CallFrame) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *CallFrame) GetBody() isCallFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *CallFrame) GetStart() *CallStart {
	if x != nil {
		if x, ok := x.Body.(*CallFrame_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *CallFrame) GetData() *CallData {
	if x != nil {
		if x, ok := x.Body.(*CallFrame_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *CallFrame) GetEnd() *CallEnd {
	if x != nil {
		if x, ok := x.Body.(*CallFrame_End); ok {
			return x.End
		}
	}
	return nil
}

func (x *CallFrame) GetCancel() *CallCancel {
	if x != nil {
		if x, ok := x.Body.(*CallFrame_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

type isCallFrame_Body interface {
	isCallFrame_Body()
}

type CallFrame_Start struct {
	Start *CallStart `protobuf:"bytes,10,opt,name=start,proto3,oneof"`
}

type CallFrame_Data struct {
	Data *CallData `protobuf:"bytes,11,opt,name=data,proto3,oneof"`
}

type CallFrame_End struct {
	End *CallEnd `protobuf:"bytes,12,opt,name=end,proto3,oneof"`
}

type CallFrame_Cancel struct {
	Cancel *CallCancel `protobuf:"bytes,13,opt,name=cancel,proto3,oneof"`
}

func (*CallFrame_Start) isCallFrame_Body() {}

func (*CallFrame_Data) isCallFrame_Body() {}

func (*CallFrame_End) isCallFrame_Body() {}

func (*CallFrame_Cancel) isCallFrame_Body() {}

// CallStart opens a call (request direction) or begins a response
// (response direction). It carries metadata only; body bytes follow in
// CallData frames.
type CallStart struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// HTTP/2-shaped pseudo-headers.
	// Request direction, required: ":method", ":path". Optional:
	// ":authority", ":scheme".
	// Response direction, required: ":status".
	PseudoHeaders map[string]string `protobuf:"bytes,1,rep,name=pseudo_headers,json=pseudoHeaders,proto3" json:"pseudo_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Regular headers, lowercased keys. Multi-valued headers are joined with
	// ", " per RFC 9110.
	Headers map[string]string `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Maximum time in milliseconds the sender will wait for the call to
	// complete. 0 means no explicit timeout (the receiver applies its own
	// ceiling). Request direction only.
	TimeoutMs int32 `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	// Opaque routing hint filled in by the server-side adapter and consumed
	// by the agent-side dispatcher. Never interpreted by the tunnel service.
	// Empty for the HTTP adapter (the agent matches on :path).
	RoutingHint []byte `protobuf:"bytes,4,opt,name=routing_hint,json=routingHint,proto3" json:"routing_hint,omitempty"`
	// Optional hint about the call shape. Lets the agent pick a backend
	// without content-type sniffing. Absence means UNARY.
	Kind          CallStart_Kind `protobuf:"varint,5,opt,name=kind,proto3,enum=cortex.axon.tunnel.v2.CallStart_Kind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallStart) Reset() {
	*x = CallStart{}
	mi := &file_tunnel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallStart) ProtoMessage() {}

func (x *CallStart) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallStart.ProtoReflect.Descriptor instead.
func (*CallStart) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{6}
}

func (x *CallStart) GetPseudoHeaders() map[string]string {
	if x != nil {
		return x.PseudoHeaders
	}
	return nil
}

func (x *CallStart) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *CallStart) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *CallStart) GetRoutingHint() []byte {
	if x != nil {
		return x.RoutingHint
	}
	return nil
}

func (x *CallStart) GetKind() CallStart_Kind {
	if x != nil {
		return x.Kind
	}
	return CallStart_UNARY
}

// CallData carries body bytes. Frames are ordered per call_id on a given
// stream; payload size must not exceed ServerHello.max_frame_bytes.
type CallData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallData) Reset() {
	*x = CallData{}
	mi := &file_tunnel_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallData) ProtoMessage() {}

func (x *CallData) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallData.ProtoReflect.Descriptor instead.
func (*CallData) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{7}
}

func (x *CallData) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// CallEnd terminates a call direction normally. Exactly one terminal frame
// (End or Cancel) is sent per call per direction.
type CallEnd struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// HTTP trailers or gRPC status trailers (grpc-status, grpc-message,
	// grpc-status-details-bin). Empty for a plain HTTP/1 response with no
	// trailers.
	Trailers      map[string]string `protobuf:"bytes,1,rep,name=trailers,proto3" json:"trailers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallEnd) Reset() {
	*x = CallEnd{}
	mi := &file_tunnel_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallEnd) ProtoMessage() {}

func (x *CallEnd) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallEnd.ProtoReflect.Descriptor instead.
func (*CallEnd) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{8}
}

func (x *CallEnd) GetTrailers() map[string]string {
	if x != nil {
		return x.Trailers
	}
	return nil
}

// CallCancel aborts a call. When the agent sends it before its response
// CallStart, code carries an HTTP status hint the server-side HTTP adapter
// uses for the error response (e.g. 404 no matching accept-file rule,
// 502 upstream unreachable, 503 agent at in-flight cap). 0 means
// unspecified (the adapter picks).
type CallCancel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallCancel) Reset() {
	*x = CallCancel{}
	mi := &file_tunnel_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallCancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallCancel) ProtoMessage() {}

func (x *CallCancel) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallCancel.ProtoReflect.Descriptor instead.
func (*CallCancel) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{9}
}

func (x *CallCancel) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CallCancel) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_tunnel_proto protoreflect.FileDescriptor

const file_tunnel_proto_rawDesc = "" +
	"\n" +
	"\ftunnel.proto\x12\x15cortex.axon.tunnel.v2\"\xca\x01\n" +
	"\vClientFrame\x12:\n" +
	"\x05hello\x18\x01 \x01(\v2\".cortex.axon.tunnel.v2.ClientHelloH\x00R\x05hello\x12@\n" +
	"\theartbeat\x18\x02 \x01(\v2 .cortex.axon.tunnel.v2.HeartbeatH\x00R\theartbeat\x126\n" +
	"\x04call\x18\x03 \x01(\v2 .cortex.axon.tunnel.v2.CallFrameH\x00R\x04callB\x05\n" +
	"\x03msg\"\xca\x01\n" +
	"\vServerFrame\x12:\n" +
	"\x05hello\x18\x01 \x01(\v2\".cortex.axon.tunnel.v2.ServerHelloH\x00R\x05hello\x12@\n" +
	"\theartbeat\x18\x02 \x01(\v2 .cortex.axon.tunnel.v2.HeartbeatH\x00R\theartbeat\x126\n" +
	"\x04call\x18\x03 \x01(\v2 .cortex.axon.tunnel.v2.CallFrameH\x00R\x04callB\x05\n" +
	"\x03msg\"\x82\x03\n" +
	"\vClientHello\x12!\n" +
	"\fbroker_token\x18\x01 \x01(\tR\vbrokerToken\x12%\n" +
	"\x0eclient_version\x18\x02 \x01(\tR\rclientVersion\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12 \n" +
	"\vintegration\x18\x04 \x01(\tR\vintegration\x12\x14\n" +
	"\x05alias\x18\x05 \x01(\tR\x05alias\x12\x1f\n" +
	"\vinstance_id\x18\x06 \x01(\tR\n" +
	"instanceId\x12(\n" +
	"\x10cortex_api_token\x18\a \x01(\tR\x0ecortexApiToken\x12L\n" +
	"\bmetadata\x18\b \x03(\v20.cortex.axon.tunnel.v2.ClientHello.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa3\x01\n" +
	"\vServerHello\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1b\n" +
	"\tstream_id\x18\x02 \x01(\tR\bstreamId\x122\n" +
	"\x15heartbeat_interval_ms\x18\x03 \x01(\x05R\x13heartbeatIntervalMs\x12&\n" +
	"\x0fmax_frame_bytes\x18\x04 \x01(\x05R\rmaxFrameBytes\".\n" +
	"\tHeartbeat\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x03R\vtimestampMs\"\x8e\x02\n" +
	"\tCallFrame\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x128\n" +
	"\x05start\x18\n" +
	" \x01(\v2 .cortex.axon.tunnel.v2.CallStartH\x00R\x05start\x125\n" +
	"\x04data\x18\v \x01(\v2\x1f.cortex.axon.tunnel.v2.CallDataH\x00R\x04data\x122\n" +
	"\x03end\x18\f \x01(\v2\x1e.cortex.axon.tunnel.v2.CallEndH\x00R\x03end\x12;\n" +
	"\x06cancel\x18\r \x01(\v2!.cortex.axon.tunnel.v2.CallCancelH\x00R\x06cancelB\x06\n" +
	"\x04body\"\xee\x03\n" +
	"\tCallStart\x12Z\n" +
	"\x0epseudo_headers\x18\x01 \x03(\v23.cortex.axon.tunnel.v2.CallStart.PseudoHeadersEntryR\rpseudoHeaders\x12G\n" +
	"\aheaders\x18\x02 \x03(\v2-.cortex.axon.tunnel.v2.CallStart.HeadersEntryR\aheaders\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\x05R\ttimeoutMs\x12!\n" +
	"\frouting_hint\x18\x04 \x01(\fR\vroutingHint\x129\n" +
	"\x04kind\x18\x05 \x01(\x0e2%.cortex.axon.tunnel.v2.CallStart.KindR\x04kind\x1a@\n" +
	"\x12PseudoHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"A\n" +
	"\x04Kind\x12\t\n" +
	"\x05UNARY\x10\x00\x12\x11\n" +
	"\rSERVER_STREAM\x10\x01\x12\x11\n" +
	"\rCLIENT_STREAM\x10\x02\x12\b\n" +
	"\x04BIDI\x10\x03\"$\n" +
	"\bCallData\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"\x90\x01\n" +
	"\aCallEnd\x12H\n" +
	"\btrailers\x18\x01 \x03(\v2,.cortex.axon.tunnel.v2.CallEnd.TrailersEntryR\btrailers\x1a;\n" +
	"\rTrailersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"8\n" +
	"\n" +
	"CallCancel\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code2e\n" +
	"\rTunnelService\x12T\n" +
	"\x06Tunnel\x12\".cortex.axon.tunnel.v2.ClientFrame\x1a\".cortex.axon.tunnel.v2.ServerFrame(\x010\x01B,Z*github.com/cortexapps/axon-server/tunnelpbb\x06proto3"

var (
	file_tunnel_proto_rawDescOnce sync.Once
	file_tunnel_proto_rawDescData []byte
)

func file_tunnel_proto_rawDescGZIP() []byte {
	file_tunnel_proto_rawDescOnce.Do(func() {
		file_tunnel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tunnel_proto_rawDesc), len(file_tunnel_proto_rawDesc)))
	})
	return file_tunnel_proto_rawDescData
}

var file_tunnel_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tunnel_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_tunnel_proto_goTypes = []any{
	(CallStart_Kind)(0), // 0: cortex.axon.tunnel.v2.CallStart.Kind
	(*ClientFrame)(nil), // 1: cortex.axon.tunnel.v2.ClientFrame
	(*ServerFrame)(nil), // 2: cortex.axon.tunnel.v2.ServerFrame
	(*ClientHello)(nil), // 3: cortex.axon.tunnel.v2.ClientHello
	(*ServerHello)(nil), // 4: cortex.axon.tunnel.v2.ServerHello
	(*Heartbeat)(nil),   // 5: cortex.axon.tunnel.v2.Heartbeat
	(*CallFrame)(nil),   // 6: cortex.axon.tunnel.v2.CallFrame
	(*CallStart)(nil),   // 7: cortex.axon.tunnel.v2.CallStart
	(*CallData)(nil),    // 8: cortex.axon.tunnel.v2.CallData
	(*CallEnd)(nil),     // 9: cortex.axon.tunnel.v2.CallEnd
	(*CallCancel)(nil),  // 10: cortex.axon.tunnel.v2.CallCancel
	nil,                 // 11: cortex.axon.tunnel.v2.ClientHello.MetadataEntry
	nil,                 // 12: cortex.axon.tunnel.v2.CallStart.PseudoHeadersEntry
	nil,                 // 13: cortex.axon.tunnel.v2.CallStart.HeadersEntry
	nil,                 // 14: cortex.axon.tunnel.v2.CallEnd.TrailersEntry
}
var file_tunnel_proto_depIdxs = []int32{
	3,  // 0: cortex.axon.tunnel.v2.ClientFrame.hello:type_name -> cortex.axon.tunnel.v2.ClientHello
	5,  // 1: cortex.axon.tunnel.v2.ClientFrame.heartbeat:type_name -> cortex.axon.tunnel.v2.Heartbeat
	6,  // 2: cortex.axon.tunnel.v2.ClientFrame.call:type_name -> cortex.axon.tunnel.v2.CallFrame
	4,  // 3: cortex.axon.tunnel.v2.ServerFrame.hello:type_name -> cortex.axon.tunnel.v2.ServerHello
	5,  // 4: cortex.axon.tunnel.v2.ServerFrame.heartbeat:type_name -> cortex.axon.tunnel.v2.Heartbeat
	6,  // 5: cortex.axon.tunnel.v2.ServerFrame.call:type_name -> cortex.axon.tunnel.v2.CallFrame
	11, // 6: cortex.axon.tunnel.v2.ClientHello.metadata:type_name -> cortex.axon.tunnel.v2.ClientHello.MetadataEntry
	7,  // 7: cortex.axon.tunnel.v2.CallFrame.start:type_name -> cortex.axon.tunnel.v2.CallStart
	8,  // 8: cortex.axon.tunnel.v2.CallFrame.data:type_name -> cortex.axon.tunnel.v2.CallData
	9,  // 9: cortex.axon.tunnel.v2.CallFrame.end:type_name -> cortex.axon.tunnel.v2.CallEnd
	10, // 10: cortex.axon.tunnel.v2.CallFrame.cancel:type_name -> cortex.axon.tunnel.v2.CallCancel
	12, // 11: cortex.axon.tunnel.v2.CallStart.pseudo_headers:type_name -> cortex.axon.tunnel.v2.CallStart.PseudoHeadersEntry
	13, // 12: cortex.axon.tunnel.v2.CallStart.headers:type_name -> cortex.axon.tunnel.v2.CallStart.HeadersEntry
	0,  // 13: cortex.axon.tunnel.v2.CallStart.kind:type_name -> cortex.axon.tunnel.v2.CallStart.Kind
	14, // 14: cortex.axon.tunnel.v2.CallEnd.trailers:type_name -> cortex.axon.tunnel.v2.CallEnd.TrailersEntry
	1,  // 15: cortex.axon.tunnel.v2.TunnelService.Tunnel:input_type -> cortex.axon.tunnel.v2.ClientFrame
	2,  // 16: cortex.axon.tunnel.v2.TunnelService.Tunnel:output_type -> cortex.axon.tunnel.v2.ServerFrame
	16, // [16:17] is the sub-list for method output_type
	15, // [15:16] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_tunnel_proto_init() }
func file_tunnel_proto_init() {
	if File_tunnel_proto != nil {
		return
	}
	file_tunnel_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientFrame_Hello)(nil),
		(*ClientFrame_Heartbeat)(nil),
		(*ClientFrame_Call)(nil),
	}
	file_tunnel_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerFrame_Hello)(nil),
		(*ServerFrame_Heartbeat)(nil),
		(*ServerFrame_Call)(nil),
	}
	file_tunnel_proto_msgTypes[5].OneofWrappers = []any{
		(*CallFrame_Start)(nil),
		(*CallFrame_Data)(nil),
		(*CallFrame_End)(nil),
		(*CallFrame_Cancel)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tunnel_proto_rawDesc), len(file_tunnel_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tunnel_proto_goTypes,
		DependencyIndexes: file_tunnel_proto_depIdxs,
		EnumInfos:         file_tunnel_proto_enumTypes,
		MessageInfos:      file_tunnel_proto_msgTypes,
	}.Build()
	File_tunnel_proto = out.File
	file_tunnel_proto_goTypes = nil
	file_tunnel_proto_depIdxs = nil
}
