// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: tunnel.proto

package tunnelpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Client → Server envelope
type TunnelClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*TunnelClientMessage_Hello
	//	*TunnelClientMessage_Heartbeat
	//	*TunnelClientMessage_HttpResponse
	Message       isTunnelClientMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelClientMessage) Reset() {
	*x = TunnelClientMessage{}
	mi := &file_tunnel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelClientMessage) ProtoMessage() {}

func (x *TunnelClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelClientMessage.ProtoReflect.Descriptor instead.
func (*TunnelClientMessage) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{0}
}

func (x *TunnelClientMessage) GetMessage() isTunnelClientMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *TunnelClientMessage) GetHello() *ClientHello {
	if x != nil {
		if x, ok := x.Message.(*TunnelClientMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *TunnelClientMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Message.(*TunnelClientMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *TunnelClientMessage) GetHttpResponse() *HttpResponse {
	if x != nil {
		if x, ok := x.Message.(*TunnelClientMessage_HttpResponse); ok {
			return x.HttpResponse
		}
	}
	return nil
}

type isTunnelClientMessage_Message interface {
	isTunnelClientMessage_Message()
}

type TunnelClientMessage_Hello struct {
	Hello *ClientHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type TunnelClientMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type TunnelClientMessage_HttpResponse struct {
	HttpResponse *HttpResponse `protobuf:"bytes,3,opt,name=http_response,json=httpResponse,proto3,oneof"`
}

func (*TunnelClientMessage_Hello) isTunnelClientMessage_Message() {}

func (*TunnelClientMessage_Heartbeat) isTunnelClientMessage_Message() {}

func (*TunnelClientMessage_HttpResponse) isTunnelClientMessage_Message() {}

// Server → Client envelope
type TunnelServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*TunnelServerMessage_Hello
	//	*TunnelServerMessage_Heartbeat
	//	*TunnelServerMessage_HttpRequest
	Message       isTunnelServerMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelServerMessage) Reset() {
	*x = TunnelServerMessage{}
	mi := &file_tunnel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelServerMessage) ProtoMessage() {}

func (x *TunnelServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelServerMessage.ProtoReflect.Descriptor instead.
func (*TunnelServerMessage) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{1}
}

func (x *TunnelServerMessage) GetMessage() isTunnelServerMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *TunnelServerMessage) GetHello() *ServerHello {
	if x != nil {
		if x, ok := x.Message.(*TunnelServerMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *TunnelServerMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Message.(*TunnelServerMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *TunnelServerMessage) GetHttpRequest() *HttpRequest {
	if x != nil {
		if x, ok := x.Message.(*TunnelServerMessage_HttpRequest); ok {
			return x.HttpRequest
		}
	}
	return nil
}

type isTunnelServerMessage_Message interface {
	isTunnelServerMessage_Message()
}

type TunnelServerMessage_Hello struct {
	Hello *ServerHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type TunnelServerMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type TunnelServerMessage_HttpRequest struct {
	HttpRequest *HttpRequest `protobuf:"bytes,3,opt,name=http_request,json=httpRequest,proto3,oneof"`
}

func (*TunnelServerMessage_Hello) isTunnelServerMessage_Message() {}

func (*TunnelServerMessage_Heartbeat) isTunnelServerMessage_Message() {}

func (*TunnelServerMessage_HttpRequest) isTunnelServerMessage_Message() {}

// ClientHello is the first message sent by the client after opening a stream.
// It carries identity information and the Cortex-API-issued broker token.
type ClientHello struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Cortex-API-issued token, used for BROKER_SERVER dispatch routing.
	BrokerToken string `protobuf:"bytes,1,opt,name=broker_token,json=brokerToken,proto3" json:"broker_token,omitempty"`
	// Client software version.
	ClientVersion string `protobuf:"bytes,2,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	// Tenant identifier from Cortex API registration.
	TenantId string `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Integration type, e.g. "github", "jira".
	Integration string `protobuf:"bytes,4,opt,name=integration,proto3" json:"integration,omitempty"`
	// Integration alias name.
	Alias string `protobuf:"bytes,5,opt,name=alias,proto3" json:"alias,omitempty"`
	// Unique agent instance ID (from config.InstanceId).
	InstanceId string `protobuf:"bytes,6,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	// Cortex API token for optional server-side JWT validation.
	CortexApiToken string `protobuf:"bytes,7,opt,name=cortex_api_token,json=cortexApiToken,proto3" json:"cortex_api_token,omitempty"`
	// Arbitrary metadata.
	Metadata      map[string]string `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientHello) Reset() {
	*x = ClientHello{}
	mi := &file_tunnel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientHello) ProtoMessage() {}

func (x *ClientHello) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientHello.ProtoReflect.Descriptor instead.
func (*ClientHello) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{2}
}

func (x *ClientHello) GetBrokerToken() string {
	if x != nil {
		return x.BrokerToken
	}
	return ""
}

func (x *ClientHello) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *ClientHello) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ClientHello) GetIntegration() string {
	if x != nil {
		return x.Integration
	}
	return ""
}

func (x *ClientHello) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *ClientHello) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *ClientHello) GetCortexApiToken() string {
	if x != nil {
		return x.CortexApiToken
	}
	return ""
}

func (x *ClientHello) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ServerHello is the response to ClientHello.
type ServerHello struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server hostname (HOSTNAME env var, or UUID fallback).
	// Client uses this for metrics tagging and to detect duplicate connections
	// to the same server instance (for multi-tunnel dedup).
	ServerId string `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	// Interval at which the server sends heartbeats.
	// Client should respond within 2x this interval.
	HeartbeatIntervalMs int32 `protobuf:"varint,2,opt,name=heartbeat_interval_ms,json=heartbeatIntervalMs,proto3" json:"heartbeat_interval_ms,omitempty"`
	// Server-generated UUID for this specific stream.
	// Used in BROKER_SERVER client-connected/deleted notifications
	// to distinguish multiple streams for the same token.
	StreamId      string `protobuf:"bytes,3,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerHello) Reset() {
	*x = ServerHello{}
	mi := &file_tunnel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerHello) ProtoMessage() {}

func (x *ServerHello) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerHello.ProtoReflect.Descriptor instead.
func (*ServerHello) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{3}
}

func (x *ServerHello) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ServerHello) GetHeartbeatIntervalMs() int32 {
	if x != nil {
		return x.HeartbeatIntervalMs
	}
	return 0
}

func (x *ServerHello) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

// Heartbeat is sent by both sides to verify tunnel liveness.
type Heartbeat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unix timestamp in milliseconds.
	TimestampMs   int64 `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_tunnel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{4}
}

func (x *Heartbeat) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

// HttpRequest is an HTTP request dispatched from the server to the client.
// Large bodies are chunked: the first chunk carries method/path/headers,
// subsequent chunks carry only body/chunk_index/is_final.
type HttpRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique request identifier for correlating responses.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// HTTP method (GET, POST, PUT, DELETE, etc.).
	Method string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	// Request path (e.g. "/api/v1/repos").
	Path string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	// HTTP headers. Only set on first chunk (chunk_index=0).
	Headers map[string]string `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Request body chunk.
	Body []byte `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	// Zero-based chunk index.
	ChunkIndex int32 `protobuf:"varint,6,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	// True if this is the last chunk for this request.
	IsFinal bool `protobuf:"varint,7,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	// Maximum time in milliseconds the server will wait for a response.
	// Client should use this as a deadline for request execution.
	// Only set on first chunk (chunk_index=0). 0 means no explicit timeout.
	TimeoutMs     int32 `protobuf:"varint,8,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpRequest) Reset() {
	*x = HttpRequest{}
	mi := &file_tunnel_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpRequest) ProtoMessage() {}

func (x *HttpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpRequest.ProtoReflect.Descriptor instead.
func (*HttpRequest) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{5}
}

func (x *HttpRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *HttpRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HttpRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HttpRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HttpRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *HttpRequest) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *HttpRequest) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *HttpRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

// HttpResponse is an HTTP response sent from the client back to the server.
// Large bodies are chunked: the first chunk carries status_code/headers,
// subsequent chunks carry only body/chunk_index/is_final.
type HttpResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Must match the request_id of the corresponding HttpRequest.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// HTTP status code. Only set on first chunk (chunk_index=0).
	StatusCode int32 `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	// HTTP response headers. Only set on first chunk (chunk_index=0).
	Headers map[string]string `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Response body chunk.
	Body []byte `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	// Zero-based chunk index.
	ChunkIndex int32 `protobuf:"varint,5,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	// True if this is the last chunk for this response.
	IsFinal       bool `protobuf:"varint,6,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpResponse) Reset() {
	*x = HttpResponse{}
	mi := &file_tunnel_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpResponse) ProtoMessage() {}

func (x *HttpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tunnel_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpResponse.ProtoReflect.Descriptor instead.
func (*HttpResponse) Descriptor() ([]byte, []int) {
	return file_tunnel_proto_rawDescGZIP(), []int{6}
}

func (x *HttpResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *HttpResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *HttpResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HttpResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *HttpResponse) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *HttpResponse) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

var File_tunnel_proto protoreflect.FileDescriptor

const file_tunnel_proto_rawDesc = "" +
	"\n" +
	"\ftunnel.proto\x12\x12cortex.axon.tunnel\"\xe1\x01\n" +
	"\x13TunnelClientMessage\x127\n" +
	"\x05hello\x18\x01 \x01(\v2\x1f.cortex.axon.tunnel.ClientHelloH\x00R\x05hello\x12=\n" +
	"\theartbeat\x18\x02 \x01(\v2\x1d.cortex.axon.tunnel.HeartbeatH\x00R\theartbeat\x12G\n" +
	"\rhttp_response\x18\x03 \x01(\v2 .cortex.axon.tunnel.HttpResponseH\x00R\fhttpResponseB\t\n" +
	"\amessage\"\xde\x01\n" +
	"\x13TunnelServerMessage\x127\n" +
	"\x05hello\x18\x01 \x01(\v2\x1f.cortex.axon.tunnel.ServerHelloH\x00R\x05hello\x12=\n" +
	"\theartbeat\x18\x02 \x01(\v2\x1d.cortex.axon.tunnel.HeartbeatH\x00R\theartbeat\x12D\n" +
	"\fhttp_request\x18\x03 \x01(\v2\x1f.cortex.axon.tunnel.HttpRequestH\x00R\vhttpRequestB\t\n" +
	"\amessage\"\xff\x02\n" +
	"\vClientHello\x12!\n" +
	"\fbroker_token\x18\x01 \x01(\tR\vbrokerToken\x12%\n" +
	"\x0eclient_version\x18\x02 \x01(\tR\rclientVersion\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12 \n" +
	"\vintegration\x18\x04 \x01(\tR\vintegration\x12\x14\n" +
	"\x05alias\x18\x05 \x01(\tR\x05alias\x12\x1f\n" +
	"\vinstance_id\x18\x06 \x01(\tR\n" +
	"instanceId\x12(\n" +
	"\x10cortex_api_token\x18\a \x01(\tR\x0ecortexApiToken\x12I\n" +
	"\bmetadata\x18\b \x03(\v2-.cortex.axon.tunnel.ClientHello.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"{\n" +
	"\vServerHello\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x122\n" +
	"\x15heartbeat_interval_ms\x18\x02 \x01(\x05R\x13heartbeatIntervalMs\x12\x1b\n" +
	"\tstream_id\x18\x03 \x01(\tR\bstreamId\".\n" +
	"\tHeartbeat\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x03R\vtimestampMs\"\xcb\x02\n" +
	"\vHttpRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12F\n" +
	"\aheaders\x18\x04 \x03(\v2,.cortex.axon.tunnel.HttpRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x05 \x01(\fR\x04body\x12\x1f\n" +
	"\vchunk_index\x18\x06 \x01(\x05R\n" +
	"chunkIndex\x12\x19\n" +
	"\bis_final\x18\a \x01(\bR\aisFinal\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\b \x01(\x05R\ttimeoutMs\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa3\x02\n" +
	"\fHttpResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\x05R\n" +
	"statusCode\x12G\n" +
	"\aheaders\x18\x03 \x03(\v2-.cortex.axon.tunnel.HttpResponse.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x12\x1f\n" +
	"\vchunk_index\x18\x05 \x01(\x05R\n" +
	"chunkIndex\x12\x19\n" +
	"\bis_final\x18\x06 \x01(\bR\aisFinal\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012o\n" +
	"\rTunnelService\x12^\n" +
	"\x06Tunnel\x12'.cortex.axon.tunnel.TunnelClientMessage\x1a'.cortex.axon.tunnel.TunnelServerMessage(\x010\x01B,Z*github.com/cortexapps/axon-server/tunnelpbb\x06proto3"

var (
	file_tunnel_proto_rawDescOnce sync.Once
	file_tunnel_proto_rawDescData []byte
)

func file_tunnel_proto_rawDescGZIP() []byte {
	file_tunnel_proto_rawDescOnce.Do(func() {
		file_tunnel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tunnel_proto_rawDesc), len(file_tunnel_proto_rawDesc)))
	})
	return file_tunnel_proto_rawDescData
}

var file_tunnel_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_tunnel_proto_goTypes = []any{
	(*TunnelClientMessage)(nil), // 0: cortex.axon.tunnel.TunnelClientMessage
	(*TunnelServerMessage)(nil), // 1: cortex.axon.tunnel.TunnelServerMessage
	(*ClientHello)(nil),         // 2: cortex.axon.tunnel.ClientHello
	(*ServerHello)(nil),         // 3: cortex.axon.tunnel.ServerHello
	(*Heartbeat)(nil),           // 4: cortex.axon.tunnel.Heartbeat
	(*HttpRequest)(nil),         // 5: cortex.axon.tunnel.HttpRequest
	(*HttpResponse)(nil),        // 6: cortex.axon.tunnel.HttpResponse
	nil,                         // 7: cortex.axon.tunnel.ClientHello.MetadataEntry
	nil,                         // 8: cortex.axon.tunnel.HttpRequest.HeadersEntry
	nil,                         // 9: cortex.axon.tunnel.HttpResponse.HeadersEntry
}
var file_tunnel_proto_depIdxs = []int32{
	2,  // 0: cortex.axon.tunnel.TunnelClientMessage.hello:type_name -> cortex.axon.tunnel.ClientHello
	4,  // 1: cortex.axon.tunnel.TunnelClientMessage.heartbeat:type_name -> cortex.axon.tunnel.Heartbeat
	6,  // 2: cortex.axon.tunnel.TunnelClientMessage.http_response:type_name -> cortex.axon.tunnel.HttpResponse
	3,  // 3: cortex.axon.tunnel.TunnelServerMessage.hello:type_name -> cortex.axon.tunnel.ServerHello
	4,  // 4: cortex.axon.tunnel.TunnelServerMessage.heartbeat:type_name -> cortex.axon.tunnel.Heartbeat
	5,  // 5: cortex.axon.tunnel.TunnelServerMessage.http_request:type_name -> cortex.axon.tunnel.HttpRequest
	7,  // 6: cortex.axon.tunnel.ClientHello.metadata:type_name -> cortex.axon.tunnel.ClientHello.MetadataEntry
	8,  // 7: cortex.axon.tunnel.HttpRequest.headers:type_name -> cortex.axon.tunnel.HttpRequest.HeadersEntry
	9,  // 8: cortex.axon.tunnel.HttpResponse.headers:type_name -> cortex.axon.tunnel.HttpResponse.HeadersEntry
	0,  // 9: cortex.axon.tunnel.TunnelService.Tunnel:input_type -> cortex.axon.tunnel.TunnelClientMessage
	1,  // 10: cortex.axon.tunnel.TunnelService.Tunnel:output_type -> cortex.axon.tunnel.TunnelServerMessage
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_tunnel_proto_init() }
func file_tunnel_proto_init() {
	if File_tunnel_proto != nil {
		return
	}
	file_tunnel_proto_msgTypes[0].OneofWrappers = []any{
		(*TunnelClientMessage_Hello)(nil),
		(*TunnelClientMessage_Heartbeat)(nil),
		(*TunnelClientMessage_HttpResponse)(nil),
	}
	file_tunnel_proto_msgTypes[1].OneofWrappers = []any{
		(*TunnelServerMessage_Hello)(nil),
		(*TunnelServerMessage_Heartbeat)(nil),
		(*TunnelServerMessage_HttpRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tunnel_proto_rawDesc), len(file_tunnel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tunnel_proto_goTypes,
		DependencyIndexes: file_tunnel_proto_depIdxs,
		MessageInfos:      file_tunnel_proto_msgTypes,
	}.Build()
	File_tunnel_proto = out.File
	file_tunnel_proto_goTypes = nil
	file_tunnel_proto_depIdxs = nil
}
