package acceptfile

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"time"

	"go.uber.org/zap"
)

// Plugin is an extension to the accept file system that allows some values in the
// accept file to be dynamically generated by executing an executable on the local system.
//
// It is currently only supported for headers.
//
// The format of plugin invocations in the accept file is: `${plugin:myplugin}`, where
// `myplugin` is the name of the executable in the provided directories specified by
// config.AgentConfig.PluginDirs.  The default is the `./plugins` directory in the agent's working directory,
// but this can be overridden by setting the `PLUGIN_DIRS` environment variable.
type Plugin struct {
	Name     string
	FullPath string
	Logger   *zap.Logger
}

func NewPlugin(name, fullPath string, logger *zap.Logger) Plugin {
	_, err := os.Stat(fullPath)
	if err != nil {
		logger.Panic("Failed to stat plugin file", zap.String("path", fullPath),
			zap.Error(err))
	}
	return Plugin{
		Name:     name,
		FullPath: fullPath,
		Logger:   logger.Named("plugin-" + name),
	}
}

func FindPlugin(name string, dirs []string, logger *zap.Logger) (Plugin, error) {
	// searches for the plugin in the provided directories
	for _, dir := range dirs {
		fullPath := dir + "/" + name
		if _, err := exec.LookPath(fullPath); err == nil {

			return NewPlugin(name, fullPath, logger), nil
		}
	}
	return Plugin{}, fmt.Errorf("plugin %q not found in directories: %v", name, dirs)
}

func (p Plugin) Execute() (string, error) {

	// executes the plugin and returns the output from stdout

	cmd := exec.Command(p.FullPath)
	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	now := time.Now()
	err := cmd.Run()

	if err != nil {
		p.Logger.Error("Plugin execution failed",
			zap.String("path", p.FullPath),
			zap.Error(err),
			zap.String("stderr", stderr.String()),
			zap.String("stdout", stdout.String()),
			zap.Int("exit-code", cmd.ProcessState.ExitCode()),
		)
		return "", fmt.Errorf("failed to execute %q (%v), output was:\nstderr: %s, stdout:%s", p.FullPath, err, stderr.String(), stdout.String())
	} else {
		duration := time.Since(now)
		p.Logger.Info("Executed plugin", zap.String("path", p.FullPath), zap.Duration("duration", duration))
	}
	return stdout.String(), nil

}
