FROM debian:stable-slim

# Install NodeJS and Snyk Broker
ENV NODE_VERSION=20
ARG SNYK_BROKER_VERSION=v1.0.6-axon
RUN apt update && apt install -y git wget && \
    wget -q -O - https://deb.nodesource.com/setup_${NODE_VERSION}.x | bash - && \
    apt install -y nodejs && \
    npm install --global npm@latest typescript@4.9.3

RUN git clone https://github.com/cortexapps/snyk-broker.git /tmp/snyk-broker && \
    cd /tmp/snyk-broker && \
    git checkout ${SNYK_BROKER_VERSION} && \
    npm install && \
    cp -r . /usr/local/snyk-broker && \
    cd /usr/local/snyk-broker && \
    npm install --global . && \
    npm prune --omit=dev && \
    rm -rf /tmp/snyk-broker

ENV PATH="/usr/local/lib/node_modules/.bin:${PATH}"

ENTRYPOINT ["snyk-broker"]
CMD ["server"]
