name: Python SDK Test
on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  test-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            python:
              - 'sdks/python/**'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Poetry
        uses: snok/install-poetry@v1.3.4

      - name: Install Protobuf
        run: |
          sudo apt install -y protobuf-compiler

      - name: Run Linter
        run: |
          cd sdks/python
          make all
          make lint    

      - name: Run tests
        run: |
          cd sdks/python
          make all
          make test
