name: Validate Accept Filters

on:
  push:
    branches:
      - '**'
    paths:
      - 'agent/test/*.json'
      - 'agent/server/snykbroker/accept_files/**'


jobs:
    test:
        runs-on: ubuntu-latest
    
        steps:
        - name: Checkout code
          uses: actions/checkout@v2    
        
        - name: Run Accept Filters tests
          run: make -C agent validate-filters
